In [3]:
import dgl
import torch 
import os.path as osp
import numpy as np

path = '/Users/wzq/Projects/datasets/igb_datasets/tiny'

feat_path = osp.join(path, 'processed','paper','node_feat.npy')
edge_path = osp.join(path, 'processed','paper__cites__paper','edge_index.npy')
node_label_path = osp.join(path, 'processed','paper','node_label_19.npy')

node_feat_np = np.load(feat_path)
edge_np = np.load(edge_path)
node_label_np = np.load(node_label_path)

node_features = torch.from_numpy(node_feat_np)
node_edges = torch.from_numpy(edge_np)
node_label = torch.from_numpy(node_label_np)

print(node_features)
print(node_edges)
print(node_label)

tensor([[ 0.0403, -0.0008,  0.0063,  ..., -0.0345,  0.0178,  0.0447],
        [ 0.0179, -0.0354, -0.0155,  ..., -0.0504, -0.0490, -0.0315],
        [-0.0477, -0.0102, -0.0100,  ...,  0.0467, -0.0511,  0.0440],
        ...,
        [ 0.0100, -0.0376,  0.0127,  ...,  0.0264,  0.0070,  0.0134],
        [-0.0349,  0.0113, -0.0057,  ...,  0.0588, -0.0412,  0.0116],
        [ 0.0017, -0.0298, -0.0174,  ..., -0.0522,  0.0024, -0.0374]])
tensor([[40073, 78219],
        [78219, 40073],
        [40073, 96565],
        ...,
        [65110, 28558],
        [28558, 32466],
        [32466, 28558]])
tensor([ 3., 12.,  8.,  ..., 12.,  8.,  3.])


In [4]:
print(node_features.shape)
print(node_features)

torch.Size([100000, 1024])
tensor([[ 0.0403, -0.0008,  0.0063,  ..., -0.0345,  0.0178,  0.0447],
        [ 0.0179, -0.0354, -0.0155,  ..., -0.0504, -0.0490, -0.0315],
        [-0.0477, -0.0102, -0.0100,  ...,  0.0467, -0.0511,  0.0440],
        ...,
        [ 0.0100, -0.0376,  0.0127,  ...,  0.0264,  0.0070,  0.0134],
        [-0.0349,  0.0113, -0.0057,  ...,  0.0588, -0.0412,  0.0116],
        [ 0.0017, -0.0298, -0.0174,  ..., -0.0522,  0.0024, -0.0374]])


In [5]:
print(node_edges.shape)
print(node_edges)

torch.Size([447416, 2])
tensor([[40073, 78219],
        [78219, 40073],
        [40073, 96565],
        ...,
        [65110, 28558],
        [28558, 32466],
        [32466, 28558]])


In [6]:
node_edges[:,0]

tensor([40073, 78219, 40073,  ..., 65110, 28558, 32466])

In [7]:
print(node_label.shape)
print(node_label)

torch.Size([100000])
tensor([ 3., 12.,  8.,  ..., 12.,  8.,  3.])


In [8]:
graph = dgl.graph((node_edges[:, 0],node_edges[:, 1]), num_nodes=node_features.shape[0])
print(graph)
print("graph: ", graph.formats())

Graph(num_nodes=100000, num_edges=447416,
      ndata_schemes={}
      edata_schemes={})
graph:  {'created': ['coo'], 'not created': ['csr', 'csc']}


In [10]:
graph.ndata['feat'] = node_features
graph.ndata['label'] = node_label

print(graph.ndata['feat'])
print(graph.ndata['label'])
print(graph)

tensor([[ 0.0403, -0.0008,  0.0063,  ..., -0.0345,  0.0178,  0.0447],
        [ 0.0179, -0.0354, -0.0155,  ..., -0.0504, -0.0490, -0.0315],
        [-0.0477, -0.0102, -0.0100,  ...,  0.0467, -0.0511,  0.0440],
        ...,
        [ 0.0100, -0.0376,  0.0127,  ...,  0.0264,  0.0070,  0.0134],
        [-0.0349,  0.0113, -0.0057,  ...,  0.0588, -0.0412,  0.0116],
        [ 0.0017, -0.0298, -0.0174,  ..., -0.0522,  0.0024, -0.0374]])
tensor([ 3., 12.,  8.,  ..., 12.,  8.,  3.])
Graph(num_nodes=100000, num_edges=447416,
      ndata_schemes={'feat': Scheme(shape=(1024,), dtype=torch.float32), 'label': Scheme(shape=(), dtype=torch.float32)}
      edata_schemes={})


In [11]:
graph = dgl.remove_self_loop(graph)
graph = dgl.add_self_loop(graph)
graph

Graph(num_nodes=100000, num_edges=547416,
      ndata_schemes={'feat': Scheme(shape=(1024,), dtype=torch.float32), 'label': Scheme(shape=(), dtype=torch.float32)}
      edata_schemes={})